--- #YAML:1.0
name:               Dancer-Plugin-Params-Normalization
version:            0.1
abstract:           Parameters Normalization plugin for Dancer
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.87
requires:
    Dancer:  1.178_01
resources:
    repository:  http://github.com/sukria/Dancer-Plugin-Params-Normalization
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
